# Generated by Django 3.2.3 on 2021-07-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='curso',
            new_name='Curso',
        ),
    ]
