# Generated by Django 3.2.3 on 2021-07-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_curso', '0002_rename_curso_description_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='Python3', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default='Prueba2'),
            preserve_default=False,
        ),
    ]
